<template><main class="container editor page-section"><div class="editor-head"><RouterLink to="/creation">← 返回创作中心</RouterLink><span class="muted">{{saving?'正在保存…':lastSaved?`已保存 ${lastSaved}`:'未保存'}}</span><div><button class="button" @click="save('draft')">保存草稿</button><button class="button button-primary" @click="save('published')">发布</button></div></div><div v-if="error" class="error">{{error}}</div><div class="editor-grid"><section><div class="field"><label for="title">标题</label><input id="title" v-model="form.title" @input="queueAutosave" placeholder="给文章一个明确的标题"></div><div class="field"><label for="excerpt">摘要</label><textarea id="excerpt" v-model="form.excerpt" placeholder="一句话说明文章内容"></textarea></div><div class="toolbar"><button v-for="tool in tools" :key="tool.label" type="button" :aria-label="tool.label" @click="insert(tool.before,tool.after)">{{tool.label}}</button></div><div class="field"><label for="markdown">正文（Markdown）</label><textarea id="markdown" ref="editor" v-model="form.contentMarkdown" @input="queueAutosave" placeholder="开始写作…"></textarea></div></section><aside class="card settings"><h2>发布设置</h2><div class="field"><label>URL slug</label><input v-model="form.slug" placeholder="自动由标题生成"></div><div class="field"><label>分类</label><select v-model="form.categorySlugs" multiple><option v-for="category in taxonomy.categories" :key="category.slug" :value="category.slug">{{category.name}}</option></select></div><div class="field"><label>标签</label><input v-model="form.tagText" placeholder="以逗号分隔，例如 Vue, 写作"></div><div class="field"><label>可见范围</label><select v-model="form.visibility"><option value="public">公开</option><option value="private">仅自己</option><option value="followers">关注者</option><option value="unlisted">仅分享链接</option></select></div><div class="field"><label>计划发布时间</label><input type="datetime-local" v-model="form.scheduledAt"></div><div class="field"><label>插入图片（必须填写说明）</label><input v-model="imageAlt" placeholder="图片替代文本"><input type="file" accept="image/*" @change="uploadImage"></div><label class="check"><input type="checkbox" v-model="form.allowComments">允许评论</label><p class="muted">发布前会明确按此范围保存；私密内容不会出现在公开列表。</p></aside></div><section class="preview"><p class="eyebrow">Preview</p><h2>{{form.title||'文章标题'}}</h2><div v-html="html"></div></section></main></template>
<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref} from 'vue'
import {useRoute,useRouter,RouterLink} from 'vue-router'
import {marked} from 'marked'
import DOMPurify from 'dompurify'
import http from '@/services/http'
const route=useRoute(),router=useRouter(),editor=ref<HTMLTextAreaElement>(),postId=ref<number|null>(null),saving=ref(false),lastSaved=ref(''),error=ref(''),timer=ref<number|undefined>(),taxonomy=ref<any>({categories:[]}),imageAlt=ref('')
const form=ref<any>({title:'',excerpt:'',contentMarkdown:'',slug:'',visibility:'private',allowComments:true,scheduledAt:'',categorySlugs:[],tagText:''})
const tools=[{label:'粗体',before:'**',after:'**'},{label:'斜体',before:'*',after:''},{label:'引用',before:'> ',after:''},{label:'列表',before:'- ',after:''},{label:'代码',before:'```\n',after:'\n```'},{label:'链接',before:'[',after:'](https://)'},{label:'图片',before:'![图片说明](',after:')'}]
const html=computed(()=>DOMPurify.sanitize(String(marked.parse(form.value.contentMarkdown||''))))
function insert(before:string,after:string){const el=editor.value;if(!el)return;const s=el.selectionStart,e=el.selectionEnd;form.value.contentMarkdown=form.value.contentMarkdown.slice(0,s)+before+form.value.contentMarkdown.slice(s,e)+after+form.value.contentMarkdown.slice(e);queueAutosave()}
async function ensureDraft(){if(!postId.value){const r=await http.post('/api/posts',form.value);postId.value=r.data.post.id}}
function queueAutosave(){if(timer.value)clearTimeout(timer.value);timer.value=window.setTimeout(async()=>{try{saving.value=true;await ensureDraft();const r=await http.post(`/api/posts/${postId.value}/autosave`,form.value);lastSaved.value=new Date(r.data.savedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}catch{error.value='自动保存失败'}finally{saving.value=false}},1500)}
async function uploadImage(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(!imageAlt.value.trim()){error.value='请先填写图片替代文本';return}try{await ensureDraft();const data=new FormData();data.append('image',file);data.append('altText',imageAlt.value);data.append('postId',String(postId.value));const media=(await http.post('/api/posts/media',data)).data.media;form.value.contentMarkdown+=`\n\n![${media.altText}](${media.url})\n`;imageAlt.value='';queueAutosave()}catch{error.value='图片上传失败'}}
async function save(status:string){saving.value=true;error.value='';try{await ensureDraft();await http.put(`/api/posts/${postId.value}`,{...form.value,tags:form.value.tagText.split(',').map((x:string)=>x.trim()),status:form.value.scheduledAt?'scheduled':status});lastSaved.value='刚刚';if(status==='published')router.push('/creation')}catch(e:any){error.value=e.response?.data?.error?.message||'保存失败，请稍后重试'}finally{saving.value=false}}
onMounted(async()=>{try{taxonomy.value=(await http.get('/api/public/taxonomy')).data}catch{}if(route.params.id){try{const p=(await http.get(`/api/posts/${route.params.id}`)).data.post;postId.value=p.id;form.value={title:p.title,excerpt:p.excerpt||'',contentMarkdown:p.content_markdown,slug:p.slug,visibility:p.visibility,allowComments:!!p.allow_comments,scheduledAt:p.scheduled_at?String(p.scheduled_at).slice(0,16):'',categorySlugs:p.categorySlugs||[],tagText:(p.tags||[]).join(', ')}}catch{error.value='无法加载文章'}}})
onBeforeUnmount(()=>{if(timer.value)clearTimeout(timer.value)})
</script>
<style scoped>.editor{max-width:1200px}.editor-head{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:24px}.editor-head>a{color:var(--accent)}.editor-head>div{display:flex;gap:8px}.editor-grid{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:24px}.toolbar{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:8px}.toolbar button{border:1px solid var(--border);background:var(--surface);color:var(--text);border-radius:6px;padding:5px 8px;font-size:.85rem}.field #markdown{min-height:440px;font-family:ui-monospace,monospace;line-height:1.6}.settings{align-self:start;padding:18px}.settings h2{font-size:1.05rem;margin-top:0}.check{display:flex;gap:8px;align-items:center}.preview{max-width:760px;margin:40px auto 0;padding-top:28px;border-top:1px solid var(--border);line-height:1.85}.preview :deep(img){max-width:100%}@media(max-width:800px){.editor-grid{grid-template-columns:1fr}.editor-head{align-items:start;flex-wrap:wrap}.settings{order:-1}}</style>
