<template>
  <main class="container page-section manager-page">
    <header class="manager-head"><div><RouterLink class="back-link" to="/creation">← 创作中心</RouterLink><p class="eyebrow">Site owner</p><h1 class="page-title">项目管理</h1><p class="muted">只管理公开作品资料；文章、系列和工作台仍沿用原有入口。</p></div><button class="button button-primary" type="button" @click="startCreate">新增项目</button></header>
    <p v-if="error" class="error" role="alert">{{ error }}</p>
    <div v-if="loading" class="empty" role="status">正在载入项目…</div>
    <section v-else-if="!projects.length" class="empty"><AppIcon name="archive" :size="24" /><p>还没有项目，先添加一个公开作品。</p><button class="button button-secondary" type="button" @click="startCreate">新增项目</button></section>
    <section v-else class="manager-list" aria-label="项目列表"><article v-for="project in projects" :key="project.id" class="card manager-item"><div><h2>{{ project.title }}</h2><p class="muted">/{{ project.slug }} · {{ project.year || '未设置年份' }}<span v-if="project.featured"> · 已精选</span></p><p>{{ project.summary || '暂无摘要' }}</p></div><div class="item-actions"><button class="button" type="button" @click="edit(project)">编辑</button><button class="button button-danger" type="button" @click="remove(project)">删除</button></div></article></section>
    <div v-if="editing" class="dialog-backdrop" @click.self="close"><form class="dialog card" role="dialog" aria-modal="true" aria-labelledby="project-form-title" @submit.prevent="save"><div class="dialog-head"><h2 id="project-form-title">{{ form.id ? '编辑项目' : '新增项目' }}</h2><button class="icon-button" type="button" aria-label="关闭" @click="close">×</button></div><div class="field"><label for="project-title">名称</label><input id="project-title" v-model="form.title" required maxlength="160" /></div><div class="field"><label for="project-slug">标识</label><input id="project-slug" v-model="form.slug" maxlength="180" placeholder="留空则按名称生成" /></div><div class="field"><label for="project-summary">摘要</label><textarea id="project-summary" v-model="form.summary" rows="2" maxlength="500" /></div><div class="field"><label for="project-description">详情</label><textarea id="project-description" v-model="form.description" rows="6" maxlength="20000" /></div><div class="form-grid"><div class="field"><label for="project-year">年份</label><input id="project-year" v-model.number="form.year" type="number" min="1900" max="2200" /></div><div class="field"><label for="project-role">职责</label><input id="project-role" v-model="form.role" maxlength="120" /></div></div><div class="field"><label for="project-stack">技术栈</label><input id="project-stack" v-model="form.techStack" placeholder="Vue, Express, MySQL" /></div><div class="form-grid"><div class="field"><label for="project-github">GitHub URL</label><input id="project-github" v-model="form.githubUrl" type="url" placeholder="https://github.com/…" /></div><div class="field"><label for="project-demo">演示 URL</label><input id="project-demo" v-model="form.demoUrl" type="url" placeholder="https://…" /></div></div><div class="field"><label for="project-cover">封面 URL</label><input id="project-cover" v-model="form.cover" placeholder="/api/public/media/123 或 https://…" /></div><label class="check"><input v-model="form.featured" type="checkbox" />在首页精选项目中展示</label><div class="dialog-actions"><button class="button" type="button" @click="close">取消</button><button class="button button-primary" type="submit" :disabled="saving">{{ saving ? '保存中…' : '保存项目' }}</button></div></form></div>
  </main>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { RouterLink } from 'vue-router'
import AppIcon from '@/components/AppIcon.vue'
import http from '@/services/http'

const projects = ref<any[]>([]); const loading = ref(true); const saving = ref(false); const error = ref(''); const editing = ref(false)
const blank = () => ({ id: null, title: '', slug: '', summary: '', description: '', cover: '', year: null, role: '', techStack: '', githubUrl: '', demoUrl: '', featured: false })
const form = reactive<any>(blank())
async function load() { loading.value = true; error.value = ''; try { projects.value = (await http.get('/api/owner/projects')).data.items || [] } catch (e: any) { error.value = e.response?.data?.error?.message || '项目暂时无法载入。' } finally { loading.value = false } }
function startCreate() { Object.assign(form, blank()); editing.value = true }
function edit(project: any) { Object.assign(form, { ...blank(), ...project, techStack: (project.tech_stack || []).join(', '), githubUrl: project.github_url || '', demoUrl: project.demo_url || '' }); editing.value = true }
function close() { if (!saving.value) editing.value = false }
async function save() { saving.value = true; error.value = ''; const payload = { title: form.title, slug: form.slug, summary: form.summary, description: form.description, cover: form.cover, year: form.year || null, role: form.role, tech_stack: String(form.techStack || '').split(',').map((item: string) => item.trim()).filter(Boolean), github_url: form.githubUrl, demo_url: form.demoUrl, featured: form.featured }; try { if (form.id) await http.put(`/api/owner/projects/${form.id}`, payload); else await http.post('/api/owner/projects', payload); editing.value = false; await load() } catch (e: any) { error.value = e.response?.data?.error?.message || '项目保存失败。' } finally { saving.value = false } }
async function remove(project: any) { if (!window.confirm(`确定删除“${project.title}”吗？`)) return; try { await http.delete(`/api/owner/projects/${project.id}`); await load() } catch (e: any) { error.value = e.response?.data?.error?.message || '项目删除失败。' } }
onMounted(load)
</script>

<style scoped>
.manager-page { max-width: 960px; }.manager-head { display: flex; align-items: end; justify-content: space-between; gap: var(--space-5); margin-bottom: var(--space-5); }.back-link { color: var(--accent); text-decoration: none; }.manager-head h1 { margin: var(--space-2) 0; }.manager-head p:last-child { margin-bottom: 0; }.manager-list { display: grid; gap: var(--space-3); }.manager-item { display: flex; align-items: start; justify-content: space-between; gap: var(--space-4); padding: var(--space-4); }.manager-item h2 { margin: 0; font-size: 1.1rem; }.manager-item p { margin: var(--space-1) 0 0; line-height: 1.6; }.item-actions { display: flex; flex: none; gap: var(--space-2); }.empty { display: grid; justify-items: center; gap: var(--space-2); padding: var(--space-8) var(--space-5); }.dialog-backdrop { position: fixed; z-index: 30; inset: 0; display: grid; place-items: center; padding: var(--space-4); background: var(--scrim); }.dialog { width: min(720px, 100%); max-height: 90vh; overflow: auto; padding: var(--space-5); background: var(--surface); }.dialog-head { display: flex; align-items: center; justify-content: space-between; }.dialog-head h2 { margin: 0; }.dialog-actions { display: flex; justify-content: end; gap: var(--space-2); margin-top: var(--space-4); }.form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-3); }.check { display: flex; align-items: center; gap: var(--space-2); margin-top: var(--space-2); }@media (max-width: 640px) { .manager-head, .manager-item { align-items: stretch; flex-direction: column; }.item-actions .button { flex: 1; }.form-grid { grid-template-columns: 1fr; } }
</style>
