<template><main class="container page-section narrow"><p class="eyebrow">Settings</p><h1 class="page-title">账户与博客设置</h1><form class="card form" @submit.prevent="save"><div v-if="message" :class="message.type==='error'?'error':'notice'">{{message.text}}</div><div class="field"><label for="blog-title">博客标题</label><input id="blog-title" v-model="form.blogTitle" placeholder="例如：张三的写作空间"></div><div class="field"><label for="blog-slug">公开主页标识</label><div class="slug"><span>/u/</span><input id="blog-slug" v-model="form.blogSlug" aria-describedby="slug-help"></div><small id="slug-help" class="muted">3–50 位小写字母、数字或连字符。</small></div><div class="field"><label for="bio">简介</label><textarea id="bio" v-model="form.bio" maxlength="1000"></textarea></div><div class="field"><label>主页可见性</label><select v-model="form.profileVisibility"><option value="public">公开</option><option value="private">私密</option></select></div><button class="button button-primary" :disabled="saving">{{saving?'保存中…':'保存设置'}}</button></form><p class="muted">账号邮箱、密码和原有个人资料仍可在 <RouterLink to="/personal/info">原个人资料页</RouterLink> 管理。</p></main></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import http from '@/services/http'
const form=ref<any>({blogTitle:'',blogSlug:'',bio:'',profileVisibility:'public',socialLinks:{}})
const saving=ref(false), message=ref<any>()
onMounted(async()=>{ try { const p=(await http.get('/api/me/blog-profile')).data.profile; form.value={blogTitle:p.blog_title||'',blogSlug:p.blog_slug||'',bio:p.bio||'',profileVisibility:p.profile_visibility||'public',socialLinks:p.social_links||{}} } catch { message.value={type:'error',text:'无法载入设置'} } })
async function save(){ saving.value=true; message.value=undefined; try { await http.put('/api/me/blog-profile',form.value); message.value={type:'success',text:'博客设置已保存'} } catch(e:any) { message.value={type:'error',text:e.response?.data?.error?.message||'保存失败'} } finally { saving.value=false } }
</script>
<style scoped>.narrow{max-width:760px}.form{padding:24px}.slug{display:flex;align-items:center;border:1px solid var(--border);border-radius:8px;background:var(--surface-raised)}.slug span{padding-left:12px;color:var(--muted)}.slug input{border:0}.notice{padding:12px;color:var(--accent);background:var(--accent-soft);border-radius:8px;margin-bottom:16px}</style>
