<template>
  <header class="site-header"><div class="container bar">
    <RouterLink class="brand" to="/" aria-label="Own-Web 首页">Own-Web<span>／</span></RouterLink>
    <button class="icon-button mobile-menu" type="button" aria-label="打开导航菜单" @click="menuOpen=!menuOpen"><AppIcon name="menu" /></button>
    <nav :class="['nav',{open:menuOpen}]" aria-label="主导航"><RouterLink v-for="link in links" :key="link.to" :to="link.to" @click="menuOpen=false">{{ link.label }}</RouterLink><RouterLink v-if="loggedIn" class="mobile-write" to="/write"><AppIcon name="pen" :size="16" />写文章</RouterLink></nav>
    <div class="actions"><RouterLink class="icon-button" to="/explore" aria-label="搜索文章"><AppIcon name="search" /></RouterLink><button class="icon-button" type="button" :aria-label="dark ? '切换浅色模式' : '切换深色模式'" @click="toggleTheme"><AppIcon :name="dark?'sun':'moon'" /></button><template v-if="!loggedIn"><RouterLink class="login" to="/login">登录</RouterLink><RouterLink class="button button-primary register" to="/register">注册</RouterLink></template><details v-else class="user-menu"><summary :aria-label="`${user.username || '用户'}的菜单`"><span class="avatar">{{ (user.username || 'U').slice(0,1) }}</span><span class="user-name">{{ user.username }}</span></summary><div class="menu-panel"><RouterLink :to="`/u/${user.blog_slug || `u-${user.id}`}`">我的主页</RouterLink><RouterLink to="/write">写文章</RouterLink><RouterLink to="/creation">文章管理</RouterLink><RouterLink to="/creation?status=draft">草稿箱</RouterLink><RouterLink to="/dashboard/bookmarks">收藏</RouterLink><RouterLink to="/dashboard/notifications">通知</RouterLink><RouterLink to="/settings">设置</RouterLink><RouterLink to="/dashboard">工作台</RouterLink><button type="button" @click="logout">退出登录</button></div></details></div>
  </div></header>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import http, { cacheAuthenticatedUser, clearCachedAuth } from '@/services/http'
import AppIcon from './AppIcon.vue'
const menuOpen=ref(false), dark=ref(localStorage.getItem('theme')==='dark'), user=ref<Record<string,any>>(JSON.parse(localStorage.getItem('userInfo')||'{}'))
const links=[{label:'首页',to:'/'},{label:'探索',to:'/explore'},{label:'创作中心',to:'/creation'},{label:'关于',to:'/about'}]
const loggedIn=computed(()=>localStorage.getItem('isLoggedIn')==='true')
function applyTheme(){const theme=dark.value?'dark':'light';document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme);window.dispatchEvent(new CustomEvent('theme-changed',{detail:{theme}}))}
function toggleTheme(){dark.value=!dark.value;applyTheme()}
async function logout(){try{await http.post('/api/logout')}finally{clearCachedAuth();window.location.assign('/')}}
onMounted(async()=>{applyTheme();try{const {data}=await http.get('/api/me');cacheAuthenticatedUser(data.user);user.value=data.user}catch{if(loggedIn.value)clearCachedAuth()}})
</script>
<style scoped>
.site-header{position:sticky;top:0;z-index:20;background:color-mix(in srgb,var(--bg),transparent 5%);border-bottom:1px solid var(--border);backdrop-filter:blur(14px)}.bar{min-height:64px;display:flex;align-items:center;gap:24px}.brand{font-weight:800;letter-spacing:-.04em;text-decoration:none;font-size:1.2rem}.brand span{color:var(--accent)}.nav{display:flex;gap:20px;align-items:center}.nav a,.login{color:var(--muted);text-decoration:none;font-size:.94rem;font-weight:650}.nav a.router-link-exact-active,.nav a:hover,.login:hover{color:var(--text)}.actions{margin-left:auto;display:flex;align-items:center;gap:8px}.icon-button{width:38px;height:38px;border:1px solid transparent;background:transparent;color:var(--text);border-radius:8px;display:inline-grid;place-items:center}.icon-button:hover{border-color:var(--border);background:var(--surface)}.register{min-height:36px;padding:0 12px}.user-menu{position:relative}.user-menu summary{display:flex;align-items:center;gap:8px;cursor:pointer;list-style:none}.user-menu summary::-webkit-details-marker{display:none}.avatar{display:grid;place-items:center;width:32px;height:32px;border-radius:50%;background:var(--accent-soft);color:var(--accent);font-weight:800}.user-name{font-weight:650;font-size:.92rem}.menu-panel{position:absolute;right:0;top:44px;width:180px;padding:6px;background:var(--surface-raised);border:1px solid var(--border);border-radius:var(--radius-sm);box-shadow:var(--shadow);display:grid}.menu-panel a,.menu-panel button{padding:9px 10px;text-align:left;text-decoration:none;color:var(--text);background:transparent;border:0;border-radius:6px;font-size:.9rem}.menu-panel a:hover,.menu-panel button:hover{background:var(--accent-soft)}.mobile-menu,.mobile-write{display:none}@media(max-width:760px){.bar{gap:10px}.mobile-menu{display:grid}.nav{display:none}.nav.open{display:grid;position:absolute;top:64px;left:0;right:0;padding:16px;background:var(--surface-raised);border-bottom:1px solid var(--border)}.mobile-write{display:flex!important;align-items:center;gap:8px}.user-name,.login,.register{display:none}.actions{gap:2px}}
</style>
